/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as CouponsValidesRouteImport } from './routes/coupons-valides'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedPaymentReturnRouteImport } from './routes/_authenticated/payment.return'
import { Route as ApiPublicHooksExpirePendingPaymentsRouteImport } from './routes/api/public/hooks/expire-pending-payments'
import { Route as ApiPublicGeniuspayNotifyRouteImport } from './routes/api/public/geniuspay/notify'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CouponsValidesRoute = CouponsValidesRouteImport.update({
  id: '/coupons-valides',
  path: '/coupons-valides',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentReturnRoute =
  AuthenticatedPaymentReturnRouteImport.update({
    id: '/payment/return',
    path: '/payment/return',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicHooksExpirePendingPaymentsRoute =
  ApiPublicHooksExpirePendingPaymentsRouteImport.update({
    id: '/api/public/hooks/expire-pending-payments',
    path: '/api/public/hooks/expire-pending-payments',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGeniuspayNotifyRoute =
  ApiPublicGeniuspayNotifyRouteImport.update({
    id: '/api/public/geniuspay/notify',
    path: '/api/public/geniuspay/notify',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coupons-valides': typeof CouponsValidesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment/return': typeof AuthenticatedPaymentReturnRoute
  '/api/public/geniuspay/notify': typeof ApiPublicGeniuspayNotifyRoute
  '/api/public/hooks/expire-pending-payments': typeof ApiPublicHooksExpirePendingPaymentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/coupons-valides': typeof CouponsValidesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/payment/return': typeof AuthenticatedPaymentReturnRoute
  '/api/public/geniuspay/notify': typeof ApiPublicGeniuspayNotifyRoute
  '/api/public/hooks/expire-pending-payments': typeof ApiPublicHooksExpirePendingPaymentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/coupons-valides': typeof CouponsValidesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/payment/return': typeof AuthenticatedPaymentReturnRoute
  '/api/public/geniuspay/notify': typeof ApiPublicGeniuspayNotifyRoute
  '/api/public/hooks/expire-pending-payments': typeof ApiPublicHooksExpirePendingPaymentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/coupons-valides'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/payment/return'
    | '/api/public/geniuspay/notify'
    | '/api/public/hooks/expire-pending-payments'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/coupons-valides'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/payment/return'
    | '/api/public/geniuspay/notify'
    | '/api/public/hooks/expire-pending-payments'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/coupons-valides'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/payment/return'
    | '/api/public/geniuspay/notify'
    | '/api/public/hooks/expire-pending-payments'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CouponsValidesRoute: typeof CouponsValidesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicGeniuspayNotifyRoute: typeof ApiPublicGeniuspayNotifyRoute
  ApiPublicHooksExpirePendingPaymentsRoute: typeof ApiPublicHooksExpirePendingPaymentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coupons-valides': {
      id: '/coupons-valides'
      path: '/coupons-valides'
      fullPath: '/coupons-valides'
      preLoaderRoute: typeof CouponsValidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payment/return': {
      id: '/_authenticated/payment/return'
      path: '/payment/return'
      fullPath: '/payment/return'
      preLoaderRoute: typeof AuthenticatedPaymentReturnRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/hooks/expire-pending-payments': {
      id: '/api/public/hooks/expire-pending-payments'
      path: '/api/public/hooks/expire-pending-payments'
      fullPath: '/api/public/hooks/expire-pending-payments'
      preLoaderRoute: typeof ApiPublicHooksExpirePendingPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/geniuspay/notify': {
      id: '/api/public/geniuspay/notify'
      path: '/api/public/geniuspay/notify'
      fullPath: '/api/public/geniuspay/notify'
      preLoaderRoute: typeof ApiPublicGeniuspayNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedPaymentReturnRoute: typeof AuthenticatedPaymentReturnRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedPaymentReturnRoute: AuthenticatedPaymentReturnRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CouponsValidesRoute: CouponsValidesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicGeniuspayNotifyRoute: ApiPublicGeniuspayNotifyRoute,
  ApiPublicHooksExpirePendingPaymentsRoute:
    ApiPublicHooksExpirePendingPaymentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
